### PR TITLE
Microverse Weather App

### PR DESCRIPTION
**Pull request by RailonA**
This project is based on using the Weather Api and displaying the information through the webpage.

### CODE REVIEW

**Review by NtwaliHeritier — COMMENTED** [review]
### **STATUS: INVALID PROJECT❌️❌️❌️**

Hello @RailonA 
This is a great project, however I have to invalidate it because of incorrect gitflow. The correct form would be to open a PR to merge to development, since it would be the default branch.

Kindly fix it and open a new PR👍️👍️

Happy coding💻️💻️💻️

**Comment by RailonA** [comment]
I have updated the default branch to developer branch as well as the merge branch of this pull request to developer.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Invalid :red_circle: 
Please, make sure that GitHub Action is running. Instead of having .github/workdlows, you should have .github/workflows.
Ask for a new CR when you are ready.

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  - All issues raised from the previous reviews are addressed. 💯 


- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
